name: Lint

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup latest CPython
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel black
          pip install -U -r requirements.txt

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Instal pyright
        run: |
          npm install -g pyright

      - name: Run pyright
        run: |
          pyright || echo 'Pyright exited'

      - name: Run black
        run: |
          black --check --verbose --skip-string-normalization .
